include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false # Allow print statements, useful for debugging
    # unused_local_variable: ignore # Ignore warnings about unused local variables
    always_declare_return_types: true # Ensure all methods have a return type
    prefer_const_constructors: true # Prefer const constructors for better performance
    avoid_unnecessary_containers: true # Avoid redundant containers in UI
    use_key_in_widget_constructors: true # Enforce using keys in widget constructors
    prefer_final_fields: true # Use `final` for fields that are not reassigned
    sort_child_properties_last: true # Improve readability of widget tree definitions

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - .dart_tool/**
    - gen/**
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    unused_import: warning
    deprecated_member_use: warning
    unnecessary_cast: ignore