include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false # Allow print statements, useful for debugging
    # unused_local_variable: ignore # Ignore warnings about unused local variables
    always_declare_return_types: true # Ensure all methods have a return type
    prefer_const_constructors: true # Prefer const constructors for better performance
    avoid_unnecessary_containers: true # Avoid redundant containers in UI
    use_key_in_widget_constructors: true # Enforce using keys in widget constructors
    prefer_final_fields: true # Use `final` for fields that are not reassigned
    sort_child_properties_last: true # Improve readability of widget tree definitions

analyzer:
  exclude:
    - build/** # Exclude generated files in the build directory
    - .dart_tool/** # Exclude Dart tool-generated files
    - gen/** # Exclude other generated code, if any
  errors:
    invalid_annotation_target: ignore # Ignore warnings for invalid annotations
    missing_required_param: error # Catch missing required parameters early
    unused_import: warning # Flag unused imports but at a warning level
    deprecated_member_use: warning # Warn about usage of deprecated members
    unnecessary_cast: ignore # Ignore unnecessary casts for simpler code

# Optional: Stronger type safety
strong-mode:
  implicit-casts: false # Prevent implicit casting, requiring explicit casts
  implicit-dynamic: false # Disable implicit dynamic typing for better type safety