# Shorebird commands
shorebird_release: ## Compile APK and release to Shorebird
	shorebird release android --artifact=apk

shorebird_patch: ## Create a patch and publish it to Shorebird
	shorebird patch android

