# Shorebird commands
release_android: ## Compile APK and release to Shorebird
	shorebird release android --artifact=apk

patch_android: ## Create a patch and publish it to Shorebird
	shorebird patch android

patch_windows: ## Create a patch and publish it to Shorebird
  shorebird patch windows --platforms=windows --release-version=0.5.2+1

