enum CommunicationSubject { pupil, tutor1, tutor2 }

enum PupilIdentityStreamRole { sender, receiver }

enum PupilSortMode {
  sortByName,
  sortByMissedExcused,
  sortByMissedUnexcused,
  sortByContacted,
  sortByLate,
  sortByCredit,
  sortByCreditEarned,
  sortByGoneHome,
  sortBySchooldayEvents,
  sortByLastSchooldayEvent,
  sortByLastNonProcessedSchooldayEvent,
}

Map<PupilSortMode, bool> initialSortModeValues = {
  PupilSortMode.sortByName: true,
  PupilSortMode.sortByMissedExcused: false,
  PupilSortMode.sortByMissedUnexcused: false,
  PupilSortMode.sortByContacted: false,
  PupilSortMode.sortByLate: false,
  PupilSortMode.sortByCredit: false,
  PupilSortMode.sortByCreditEarned: false,
  PupilSortMode.sortByGoneHome: false,
  PupilSortMode.sortBySchooldayEvents: false,
  PupilSortMode.sortByLastSchooldayEvent: false,
  PupilSortMode.sortByLastNonProcessedSchooldayEvent: false,
};

// SchoolGrade is defined in school_data_hub_client (generated by Serverpod)

enum ReligionCourse {
  islam('isl.'),
  catholic('kath.'),
  none('andere');

  static const stringToValue = {
    'isl.': ReligionCourse.islam,
    'röm.kath.': ReligionCourse.catholic,
    'andere': ReligionCourse.none,
  };

  final String value;
  const ReligionCourse(this.value);
}

enum FamilyLanguage {
  turkish('Türkisch'),
  arabic('Arabisch'),
  albanian('Albanisch'),
  other('Andere');

  static const stringToValue = {
    'Türkisch': FamilyLanguage.turkish,
    'Arabisch': FamilyLanguage.arabic,
    'Albanisch': FamilyLanguage.albanian,
    'Andere': FamilyLanguage.other,
  };
  final String value;
  const FamilyLanguage(this.value);
}

enum Gender {
  male('m'),
  female('w');

  static const stringToValue = {'m': Gender.male, 'w': Gender.female};

  final String value;
  const Gender(this.value);
}

enum AfterSchoolCareWeekday { monday, tuesday, wednesday, thursday, friday }

/// Converts a DateTime to AfterSchoolCareWeekday
/// Handles UTC dates by converting to local time first
/// Returns null if the date is not a weekday (Saturday or Sunday)
AfterSchoolCareWeekday? dateTimeToAfterSchoolCareWeekday(DateTime date) {
  // Convert UTC to local time to get the correct weekday for the user's timezone
  final localDate = date.isUtc ? date.toLocal() : date;

  // DateTime.weekday: Monday=1, Tuesday=2, ..., Friday=5, Saturday=6, Sunday=7
  switch (localDate.weekday) {
    case 1:
      return AfterSchoolCareWeekday.monday;
    case 2:
      return AfterSchoolCareWeekday.tuesday;
    case 3:
      return AfterSchoolCareWeekday.wednesday;
    case 4:
      return AfterSchoolCareWeekday.thursday;
    case 5:
      return AfterSchoolCareWeekday.friday;
    default:
      return null; // Saturday or Sunday
  }
}

enum AfterSchoolCarePickUpModality {
  alone('allein'),
  anyRelative('Verwandte'),
  anyOther('Bekannte'),
  exception('Besondere Regelung'),
  notSet('bitte wählen');

  final String value;
  const AfterSchoolCarePickUpModality(this.value);
}
