enum PupilFilter {
  afterSchoolCare,
  noAfterSchoolCare,
  entitledToEmergencyCare,
  specialInfo,
  migrationSupport,
  preSchoolRevision0,
  preSchoolRevision1,
  preSchoolRevision2,
  preSchoolRevision3,

  fiveYears,
  communicationPupil,
  communicationTutor1,
  communicationTutor2,
  onlyGirls,
  onlyBoys,
  schoolListYesResponse,
  schoolListNoResponse,
  schoolListNullResponse,
  schoolListCommentResponse,
  authorizationPositive,
  authorizationNegative,
  authorizationNoValue,
  authorizationComment,
  authorizationNoFile,
  catholicReligion,
  muslimReligion,
  turkishClass,
  arabicClass,
  albanianClass,
  otherLanguageClass,
}

Map<PupilFilter, bool> initialPupilFilterValues = {
  PupilFilter.afterSchoolCare: false,
  PupilFilter.noAfterSchoolCare: false,
  PupilFilter.entitledToEmergencyCare: false,
  PupilFilter.specialInfo: false,
  PupilFilter.migrationSupport: false,
  PupilFilter.preSchoolRevision0: false,
  PupilFilter.preSchoolRevision1: false,
  PupilFilter.preSchoolRevision2: false,
  PupilFilter.preSchoolRevision3: false,
  PupilFilter.fiveYears: false,
  PupilFilter.communicationPupil: false,
  PupilFilter.communicationTutor1: false,
  PupilFilter.communicationTutor2: false,
  PupilFilter.onlyBoys: false,
  PupilFilter.onlyGirls: false,
  PupilFilter.schoolListYesResponse: false,
  PupilFilter.schoolListNoResponse: false,
  PupilFilter.schoolListNullResponse: false,
  PupilFilter.schoolListCommentResponse: false,
  PupilFilter.authorizationPositive: false,
  PupilFilter.authorizationNegative: false,
  PupilFilter.authorizationNoValue: false,
  PupilFilter.authorizationComment: false,
  PupilFilter.authorizationNoFile: false,
  PupilFilter.catholicReligion: false,
  PupilFilter.muslimReligion: false,
  PupilFilter.turkishClass: false,
  PupilFilter.arabicClass: false,
  PupilFilter.albanianClass: false,
  PupilFilter.otherLanguageClass: false,
};
