name: school_data_hub_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  html: ^0.15.5+1
  http: ^1.4.0
  logging: ^1.3.0
  path: ^1.9.1
  serverpod: 2.9.1
  serverpod_auth_server: 2.9.1
  uml_for_serverpod: 0.0.5
  mailer: ^6.5.0

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

